/**
 * GÉNÉRÉ — ne pas modifier à la main. Régénérer avec :
 *   npx tsx scripts/build-tunisia-places.ts
 *
 * La délégation (مُعتمدية) de chaque localité du gazetteer, calculée par
 * appartenance géométrique au build.
 *
 * Ce détour existe pour que le serveur puisse étiqueter une punaise sans
 * charger les 264 tracés ADM2 : les polygones restent dans
 * ./tunisia-delegations, importé à la demande par la carte seule.
 */

/** Localité de référence → code de délégation. */
export const PLACE_DELEGATION: Record<string, string> = {
  "Aghir": "TN-82:djerba-midoun",
  "Ajim": "TN-82:djerba-ajim",
  "Ariana": "TN-12:ariana-ville",
  "Béja": "TN-31:beja-nord",
  "Ben Arous": "TN-13:ben-arous",
  "Ben Gardane": "TN-82:ben-gardane-2",
  "Béni Khiar": "TN-21:beni-khiar",
  "Bir Bouregba": "TN-21:hammamet",
  "Bizerte": "TN-23:bizerte-nord",
  "Borj Louzir": "TN-12:soukra",
  "Bou Salem": "TN-32:bousalem",
  "Carthage": "TN-11:carthage",
  "Chebba": "TN-53:chebba",
  "Chenini Nahal": "TN-81:gabes-ouest",
  "Chihia": "TN-61:sakiet-eddaier",
  "Dahmani": "TN-33:dahmani",
  "Dar Chaabane": "TN-21:dar-chaabane-el-fehri",
  "Den Den": "TN-14:manouba",
  "Djerba": "TN-82:djerba-ajim",
  "Douar Hicher": "TN-14:manouba",
  "Douz": "TN-73:douz-nord",
  "El Fahs": "TN-22:el-fahs",
  "El Menzah": "TN-11:el-menzah",
  "El Omrane": "TN-11:el-omrane",
  "Enfidha": "TN-51:enfidha",
  "Ennasr": "TN-12:ariana-ville",
  "Ezzahra": "TN-13:ezzahra",
  "Fouchana": "TN-13:mohamedia",
  "Gabès": "TN-81:gabes-ville",
  "Gafsa": "TN-71:gafsa-sud",
  "Gammarth": "TN-11:la-marsa",
  "Ghannouch": "TN-81:ghanouch",
  "Ghomrassen": "TN-83:ghomrassen",
  "Grombalia": "TN-21:grombalia",
  "Haffouz": "TN-41:haffouz",
  "Hammam Lif": "TN-13:hammam-lif",
  "Hammam Sousse": "TN-51:hammam-sousse",
  "Hammamet": "TN-21:hammamet",
  "Houmt Souk": "TN-82:djerba-houmet-souk",
  "Jendouba": "TN-32:jendouba-sud",
  "Kairouan": "TN-41:kairouan-nord",
  "Kalaa Kebira": "TN-51:kalaa-kebira",
  "Kasserine": "TN-42:ezzouhour",
  "Kébili": "TN-73:kebili-nord",
  "Kélibia": "TN-21:kelibia",
  "Kerkennah": "TN-61:kerkennah",
  "Korba": "TN-21:korba",
  "Ksar Hellal": "TN-52:ksar-hellal",
  "Ksour Essef": "TN-53:ksour-essef",
  "La Goulette": "TN-11:la-goulette",
  "La Marsa": "TN-11:la-marsa",
  "La Soukra": "TN-12:soukra",
  "Le Bardo": "TN-11:le-bardo",
  "Le Kef": "TN-33:kef-est",
  "Le Kram": "TN-11:le-kram",
  "Mahdia": "TN-53:mahdia",
  "Mahrès": "TN-61:el-mahres",
  "Makthar": "TN-34:makthar",
  "Manouba": "TN-14:manouba",
  "Mareth": "TN-81:mareth",
  "Mateur": "TN-23:mateur",
  "Médenine": "TN-82:medenine-sud",
  "Mégrine": "TN-13:megrine",
  "Menzel Bourguiba": "TN-23:menzel-bourguiba",
  "Menzel Jemil": "TN-23:menzel-jemil",
  "Menzel Temime": "TN-21:menzel-temime",
  "Metlaoui": "TN-71:metlaoui",
  "Midoun": "TN-82:djerba-midoun",
  "Mohamedia": "TN-13:mohamedia",
  "Moknine": "TN-52:moknine",
  "Monastir": "TN-52:monastir",
  "Montplaisir": "TN-11:cite-el-khadra",
  "Mornag": "TN-13:mornag",
  "Mornaguia": "TN-14:mornaguia",
  "Msaken": "TN-51:msaken",
  "Nabeul": "TN-21:nabeul",
  "Nefta": "TN-72:hazoua",
  "Nefza": "TN-31:nefza",
  "Oued Ellil": "TN-14:oued-ellil",
  "Port El Kantaoui": "TN-51:hammam-sousse",
  "Radès": "TN-13:rades",
  "Raoued": "TN-12:raoued",
  "Ras Jebel": "TN-23:ras-jebel",
  "Redeyef": "TN-71:redeyef",
  "Regueb": "TN-43:regueb",
  "Remada": "TN-83:remada",
  "Route Gremda": "TN-61:sfax-sud",
  "Sahline": "TN-52:sahline",
  "Sakiet Eddaier": "TN-61:sakiet-eddaier",
  "Sakiet Ezzit": "TN-61:sakiet-ezzit",
  "Sbeitla": "TN-42:sbeitla",
  "Sfax": "TN-61:sfax-ville",
  "Sidi Bou Saïd": "TN-11:carthage",
  "Sidi Bouzid": "TN-43:sidi-bouzid-ouest",
  "Sidi Thabet": "TN-12:de-sidi-thabet",
  "Siliana": "TN-34:siliana-nord",
  "Soliman": "TN-21:soliman",
  "Sousse": "TN-51:sousse-medina",
  "Tabarka": "TN-32:tabarka",
  "Tataouine": "TN-83:tataouine-nord",
  "Testour": "TN-31:testour",
  "Tozeur": "TN-72:tozeur",
  "Tunis": "TN-11:bab-bhar",
  "Yasmine Hammamet": "TN-21:hammamet",
  "Zaghouan": "TN-22:zaghouan",
  "Zarzis": "TN-82:zarzis",
};
